name: Run shop E2E tests # TODO: pass branches names for this to upload code not always from main
on: workflow_call
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Upload frontend repository
        uses: actions/checkout@v3
        with:
          path: budoman-frontend
      - name: Create .env file for frontend application
        working-directory: budoman-frontend
        run: |
          cat <<EOF > .env
          API_URL=${{ secrets.BUDOMAN_FRONTEND_API_URL }}
          AWS_REGION=${{ secrets.BUDOMAN_FRONTEND_AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.BUDOMAN_FRONTEND_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.BUDOMAN_FRONTEND_AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET=${{ secrets.BUDOMAN_FRONTEND_AWS_BUCKET }}
          EOF
      - name: Upload backend repository
        uses: actions/checkout@v3
        with:
          repository: kiwi439/budoman-backend
          path: budoman-backend
      - name: Create .env file for backend application
        working-directory: budoman-backend
        run: |
          cat <<EOF > .env
          AWS_REGION=${{ secrets.BUDOMAN_BACKEND_AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.BUDOMAN_BACKEND_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.BUDOMAN_BACKEND_AWS_SECRET_ACCESS_KEY }}
          SMTP_PASSWORD=${{ secrets.BUDOMAN_BACKEND_SMTP_PASSWORD }}
          SMTP_AUTHENTICATION=${{ secrets.BUDOMAN_BACKEND_SMTP_AUTHENTICATION }}
          DATABASE_HOST=${{ secrets.BUDOMAN_BACKEND_DATABASE_HOST }}
          DATABASE_USER_NAME=${{ secrets.BUDOMAN_BACKEND_DATABASE_USER_NAME }}
          DATABASE_PASSWORD=${{ secrets.BUDOMAN_BACKEND_DATABASE_PASSWORD }}
          DATABASE_PORT=${{ secrets.BUDOMAN_BACKEND_DATABASE_PORT }}
          REDIS_URL=${{ secrets.BUDOMAN_BACKEND_REDIS_URL }}
          SCHEMA_REGISTRY_URL=${{ secrets.BUDOMAN_BACKEND_SCHEMA_REGISTRY_URL }}
          SIDEKIQ_PANEL_LOGIN=${{ secrets.BUDOMAN_BACKEND_SIDEKIQ_PANEL_LOGIN }}
          SIDEKIQ_PANEL_PASSWORD=${{ secrets.BUDOMAN_BACKEND_SIDEKIQ_PANEL_PASSWORD }}
          ROLLBAR_ACCESS_TOKEN=${{ secrets.BUDOMAN_BACKEND_ROLLBAR_ACCESS_TOKEN }}
          RAILS_ENV=test
          EOF
      - name: Run Cypress tests
        id: cypress-tests
        uses: cypress-io/github-action@v6
        with:
          start: |
            docker compose -f ../budoman-backend/docker-compose.yml up -d
            docker compose -f ./docker-compose.yml up -d
          wait-on: 'http://localhost:3003/, http://localhost:3333/'
          wait-on-timeout: 120
          command: npm run tests:shop:e2e
          working-directory: budoman-frontend
      - name: Upload Cypress screenshots
        if: failure() && steps.cypress-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: budoman-frontend/tests/e2e/screenshots
